package ie.tudublin;

import java.util.ArrayList;

import processing.core.PApplet;
import processing.data.Table;
import processing.data.TableRow;

public class Nematode extends PApplet
{
    private String name; //THIS IS ORDERED!!
	private int length;
	private int limbs;
	private String gender;
	private int eyes;


    public Nematode(TableRow row){
        this(
            row.getString("name"),
            row.getInt("length"),
            row.getInt("limbs"),
            row.getString("gender"),
            row.getInt("eyes")
        );
    }

    //Nematode constructor generated by VSC :)
    public Nematode(String name, int length, int limbs, String gender, int eyes) {
        this.name = name;
        this.length = length;
        this.limbs = limbs;
        this.gender = gender;
        this.eyes = eyes;
    }

    

    
}